version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Dependency Update"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: development
        patterns:
          - "*"
      production-dependencies:
        dependency-type: production
        patterns:
          - "*"
